---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-ddns-secrets
  namespace: cloudflare-ddns
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgA/TUZvq65D6i+uZpHyHXKZPbS0i73tj6dL9ZPpTgqXt221WC9oO8xrjlzpp6gZbFOeNIJAVQATObO5igC+W47sujnbaniUxr20i8DOk+f0ygCm5S0+wjdiGggLTD8Av4C4zIpqVA/L40Oo4PFpGOdnvEVFn/H8XMnijlvGdbqHCMxBQTOTyV8W16kRPElej0m6xyUWVHqagx6CQcMKP+V5QZwPCQVbTad/vNCk+wyfd5RAiLW1pOI3zrg0te4nYhCx+KdtfuaEsO1hNww/KgPc0xbgE5Vz/3SDJ1OuWq0ESQyOkBo3mMh/GqfA0INjVhSnNn4QBPiHc82wICoOrXlP7+igui2UPPOWiO8JaDyTVFhQVVMzKFdl2WVkBvsb/RrbaEOloDgLQzMve+2P2bHCqDzyL6Kgg4JqvQoK9n/As2Q/yTsHFOxe/bSxEjRde8bnmei2+kmhXHgwGLci8TdP+wpHouUKKuis+w7MgGvIpJvwc/RUjod5NccyUw2CkdbXlpd9pbZy3mPXn/GesLDxZKvGRJbFuNd3qqyEJYu2+AjEZvK88q1YnVGnnsWq4MCIO9q3QA3FcVuMzjwXOLFU1BdmMqdNHs/mremTdia8K7juwjvwvMGPnHQ+2Ry8Jz2FkIk4mEBVt/OhEQt1vSLvXyh791QPYqfipvETRcUUBfQFLTUpmyFYsxH1J+/HuK7cjUiG8KZjhrkFFQd8b2fMGWafWCtF1ofavsxwOY2gK8WZFvNCOH/2ExuHhgPFbCT+3KoY+g==
  template:
    metadata:
      name: cloudflare-ddns-secrets
      namespace: cloudflare-ddns
