---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secrets
  namespace: auth
spec:
  encryptedData:
    oidc-client-secret: AgCBLWzoRUJIt+O1W8tK+Ijz4M/L6ojXvH58mt7l+q4KzskWc0cpJIN54Qe0tdorMr+M1QehHNy8Ow6Wzn0SFmT237hemtjDA5tcR74T9XOHT7t2NyXt9I2+nPzl5SDUMgKKgcJfTYwaslOxERJojOguq+S5yoAY+o2xeBkOi+M+i8Ugz35c+S/Gv/KxPdc1tkH5yqYcikoPlqxL5s3O+7/mgHv60++eIgZg/gvoA4U3KaqCRmXBWE9B1uEwvbnrz4qXaIcGXAJtiCYXy0MCIaNAQO63rtmhS0gCAvahw5N9EH22oPUOBTRNwlNe+yYPECggYxonauiUybbo39JifJrm4jpjRcY8z+ITH9a8LFfi3J3IIPwWUijus52A0QlOFdLv8/cfd11Ng1mFV/a86cyed8m6vQ/HnQoWKGTTHzKcfu0O1cT2KBAn/wUyJCZb/1Leqim+HjtiE31d2qxPCqjQSWgh/M/EB4A+5aOiQ9iXyo1Sp1QSXY7WFkmFjz3VvHyLQlEDILgQcN6TPQGkt5bt0Nn1GDxaxSWon4s7hGZop4rzzjJG29fnfFZ2cJxj+uaL4PypMCcfe4hbYxGUCBmq4pv3YZN/yyycSLpImEhlk2jNUrVPc2HzfBooy4M7mGRKkBuTyUSiX3LetHSf3gms0mS7xXYZx75eJSH8vvvSEUOMZfzhczg47WD4MY+dUDLuShOBagUMr3215ylzcEszBW45wQ1w4nHXgip3ir/NM3IBQ1MhdHzH
    secret: AgAP6QGejuSE4pTIMvbVF14R8LkCOmIQX9NGLPI+Dg6Wlp7IuXVcGJjv7Wryg65dAyBRS/ksgAJhL48t3MvudVantKH9l62Xw6ACEmhcRcGvhA5nRtOzSx3oroe2oVPv/r2o6U5eKfbS1DKu0BpSZfrLzCBVhmwBfBbtiXzwd2niv4OWdluxZ2G3MvaGMAkilAg741tPYzBHmQl1Vy7w5FDlIuQW6aT/zyz6TJ+uOyyTAwwA4Wpi4C6WAwqMQpzDIx0MnMBjw07XQWfdIhLsOOOb8ZMDi26oICQj22Ez/Wy34CP1O5gLfyxIv3IQiyvVGpgWHugvnrDDRO7i0OzreTwDRQhA74D4NxIDw2eZBBRU3r4NcrhLfck3pymO/30q1AU5Wp0PxCDCnWmFefruGO8BnCKFvFdaLWlXMcSHiPaQYmskHcJM5WbKe5Go0sWJXSqegU9aKmvby8WEpZU7HO0STp/OuFNz3mpARBeTfsDG13WW8hjgclcXInrzeD9g9BKaA3xiE+GEKb+9N+aDWyQft/wKhpKBApRu4oKI46W3RSEwpHYEeej78b8akxhz5kNdgSJSQP9Virc+ZsFwKHHOfd7eBShQb7rQkmb0U6DlYmPN3QWxqzVWEjH6faD4oGToPKjqitAg3R121n+ozG2CEiIDcL41k96JqY+gfgCqArFMeDxCiUFx/eYVi6hy31qWNn1PP7MoYrexk1kg7JUJSIOW55UjRA6GmIamhH9rwA==
  template:
    metadata:
      name: auth-secrets
      namespace: auth
    type: Opaque
