---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth-secret
  namespace: auth
spec:
  encryptedData:
    users: AgCgvMWJz4krcvnVUO4tdC8dksIU/WHej4WI12Fl44O9b+gLckBVUggWUGiHqRN36nlcyao4U8fqXEBInXu1pNGR/nVoKhA7B69fJY1SyMUCYl8uBfYu3qyH1W25i9Ahi9xno+Ij0t+W8Wl2vpgR8A9O2bUi6RXGVeRq+7BqTpjGY9DY3+V0j4jhIejeTDjSJCnpZ6i7Zk2OI1M8yPMcoPXBOKU7bKYlf+IFRRridL/8X49VjxEs1QMORCIXueIB3Yi+0SvJmLrgtNablkA7frv3QtteZM0HHjVAdB44mrTCrMdAyzksEa/9GLwEdGlgehoFrEsFH9dZrM14BO1Vm6LVUqkyu89YaGkZD6NZass7smVbWX+gdep03AMHsRlGWwrhJ3uYzpsF7EKkCbTi1nSpHEyB8CRpgztqU7l7g00Qwrv5fYXVTiFWCSzryL5pUP/4VLDxxqDtfQjhWOgxHYOpnTSjWEk7cCKTKlmtlcRfrsOPp+2gGsjGeaFqj0hD8EPmYVRUqvjfm2OscoEnj6Db2iFyVYC6XDu//SWWOjWDIfQJdlF833o9aHBao7Lo5Tgj7kDn8dlv3nGKGDw7UUdFbK1tmlv0AmJc4K7Se5001nooWGMxNTcZtZd71mrqW9wjvBYVHryE/pYvXCTs4qThVqsk6litzvDguDTAyn4VRCwXeIiDQMfcTHGIyDgrdhwQJ0/9grEc5Jy8cEXgwvHoDcn+OeRnaI1wl1C3Qls18vXwZ/x/NNuVtRxD
  template:
    metadata:
      name: basic-auth-secret
      namespace: auth
    type: Opaque
