---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: 3proxy
  namespace: 3proxy
spec:
  encryptedData:
    users.cfg: AgCbzeH5hxzMeIB/GIUnzWOu2h5nDVK0JkFjVHF2Bvq5NntwwK0x4182zCr2tKhanpVZhVKFT/7E0a9tWNvJH+Xi+0YSN9hZQA6Knbk8kuqD4HzPhA/Q9vd/0oz23amfZO9Y9UtLC2g9ET1Q+RlAdXCcELjDjQpX7K0gLZXkmaUkgOLBtWNGd6Me1+Zmj4b7XD/K1k7OTNg5EDIqC4HGdxVb8igwgKdb2+pHkJMvFL93VfdYNeNwDa+oPnbmw449yraEomoaVs+IdtyTipIpzue0wzT5Cvn3pJOKe1VGuU4TgWb5/R0ZxqYHU9l9GLGY0BGzWqmCo1UtHnuchSWB4pds261J12sz79U5X9TnoA8lVHSS0i7wbnYsWDb7teLQcwygvk8wRoT498x/WBwV20v2FAynrAJ4UhWO3duXVKBGVRfT+BMSOxOUvyZXapYmGAOuuM8cHRvhNfi6/5BWihWp+L3WvVWyqtMaceNY/SOfmUBYbUvmFKoLsU6ijhFWUGuiD4inMDV5iHHJ9xxk4ffvHcTsApWjP2/H9aYYVwTNAIi1Q+DM+ricnErXvGP0vWwntgODeHHpTfBKMNmW0j4bxZuzUSrmBFWHQlR0NI4mzcAggqMuBqLQw9OjuWF0w447w5xC/WXtNmWKWHVG7sKp62USrMKybxol5EyCFsz6I0MlJrmAVA4LI2STEJAoVg5KpE9ArP0AlUF6Artqt00CLwYK7jgEVIWQC3OP3jPEmyex9gYTAFymbnEOmIaDCmTxhM0=
  template:
    metadata:
      name: 3proxy
      namespace: 3proxy
