---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosp-secrets
  namespace: mosp
spec:
  encryptedData:
    db-password: AgCxOktMvO4qE1k5384uggwLVW9qk08O2fzu3ETmTxEdXcpX+qmQV+JlTG/utIsci9kTZRGiU7utuAM+OgV2WtrN9ABX5gXt6wZ+dBtCkbEmYzbQJ3Y+lJ6PyPP3u6kSOklnci4VugeJUYnWV/hsJgIV6KYWm+SYncuo8IWECtk7Rgk2q3UaQJodIfO3mK4kR2JIrZlvBKzToXwBSLrnEEg6v6yN0VuctBO1TFnQv7YUwkFQxmU9r0huhAmOkO6Iv4aiNPsW2UzvLDvdzHaksP7hsH71FYzVWiOkap1c/gwZbazJYHBN14jLMoX0oEEtuNMgikEsh7UjTqk1qfNVqGKwED6BiTTqbvjFzcuuqLJXSThxou3QJpW0t97dEoELcj3ooo8oB+uKKQgTASajubuq2QPWCwUOl7VrUh1vv/YeoKsDAPYx5Jo1HzfkOxnWJLgyyORciIFOwjKICSUgJjMm/DvxHZG91zimnwHpLqyuYjdIs67uPtY9cwmq/vUrbuw4xVaL35gXxVqx/0/5Z0Dd2Cfwz1fCVf6Gukt809wskXgrOWI+Oht9+vIsKYsxYaVyY4B5Sz1Q8WPoZ7J53Al7ahVqSSgda6CXxkHkb4UYIPbBHje0mzoSo6VTP/rW26ORCGzJYCYcEz89Lw5w783LRvQ/mLYJ/jq0aCjK2gHaNyJdxTQDSCVi/nqVbevUdD83C8vJJrZ8HuMaPFiNmz2bCV2oVYOfhfgjXQzpFHn/vQ==
  template:
    metadata:
      name: mosp-secrets
      namespace: mosp
    type: Opaque
