apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengist
  namespace: opengist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opengist
  template:
    metadata:
      labels:
        app: opengist
    spec:
      containers:
        - name: opengist
          image: ghcr.io/thomiceli/opengist:1.14
          ports:
            - containerPort: 6157
          env:
            - name: OG_EXTERNAL_URL
              value: https://g.doany.io
            - name: OG_OIDC_PROVIDER_NAME
              value: Microsoft Entra ID
            - name: OG_OIDC_CLIENT_KEY
              value: b0fa498f-7e6a-4fe1-a1c6-16fbbb6f397e
            - name: OG_OIDC_SECRET
              valueFrom:
                secretKeyRef:
                  name: opengist-secrets
                  key: oidc-secret
            - name: OG_OIDC_DISCOVERY_URL
              value: https://login.microsoftonline.com/22ac977d-b140-4dc8-8150-90d645d3475b/v2.0/.well-known/openid-configuration
          volumeMounts:
            - name: opengist-data
              mountPath: /opengist
      volumes:
        - name: opengist-data
          persistentVolumeClaim:
            claimName: opengist-data
