---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opengist-secrets
  namespace: opengist
spec:
  encryptedData:
    oidc-secret: AgCpZ9MoY27vesg0J2fu1yGIhFVsdteQsH266sxBdlyhwOnsUMQt7uY+1Xjpv/qfYVW6oxMZY/bWo2uwNpthDviLzT781XxsPVHM9TowlRMJczcAmLh89RQdJhnNw6XzFX98ytZUSthgWb69poCWUXC0u9Vme9FlmmMKdGzBne0c6hos4IOT1/uf/GUeHv8FFUR3UlaLCeXyr03eYywUglvLhkfkH457VS/S9QAMsBNXRdlxQolK4AdWrOv7+ORYzcac6Yc4AoT8Fp6Ho+ESSPoar4ePVBe7gWnicyfYon57EnZ5bUbXsVAwD0kJsy7Z8zj/D6Hk3Q2m/x6NLdOd9+dCttTI5y8patdQJlspIJGMw7ZytHGGdDMvwB3KCqrrIqHUAU3SDx16oBauw8AsXli3IT/R+OrHccngnhlKPMgP9r7C0UZqY87oTTbBhUey0Zm4/ioySh+9WDbKWqbnfF9ECiUoV/WZoJoWFhIveXzhZse62SQ9G3kZzN0znoyuWnn5Sbtp8etaBY02JKtTOqDBFSIjIVRHJcBirb52atlOW9GRcpZPxz2csq51PO8hkjI3W+NOsvyn+R5F5q+DWQrDyw3ciinxqQD4M7h+vx1nHutVyjnQ/x9dfHhvjwpQUy8oUI6jFbmgxSvfg/V08YZbByVdak11b/mHGGn8JHt4PX691dXX1bQ/3R2ir2cwcDhiCGcI067WXwzmH4rKb/ZRtaXD1cPyehAGiZN1Gc4x8qRCWWlfn53/
  template:
    metadata:
      name: opengist-secrets
      namespace: opengist
    type: Opaque
