apiVersion: v1
kind: Service
metadata:
  name: adguardhome-web
  namespace: adguardhome
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: adguardhome-insecure-transport@kubernetescrd
spec:
  selector:
    app: adguardhome
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: adguardhome
spec:
  insecureSkipVerify: true
